# Generated by Django 6.1 on 2026-08-20 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('estaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='cjasPolls.estaca')),
            ],
            options={
                'db_table': 'unidades',
                'ordering': ['nome'],
                'constraints': [models.UniqueConstraint(fields=('estaca', 'nome'), name='unique_unidade_estaca')],
            },
        ),
    ]
