# Generated by Django 6.1 on 2026-08-20 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0002_add_unidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioCJAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=250)),
                ('vai_cjas', models.BooleanField()),
                ('motivo_nao_participacao', models.CharField(blank=True, choices=[('TRABALHO', 'Vou trabalhar durante o Cjas'), ('VIAGEM', 'Vou viajar para outro lugar durante o Cjas'), ('NAO_QUERO', 'Não quero mais participar'), ('OUTROS', 'Outro')], max_length=30, null=True)),
                ('motivos_outros', models.TextField(blank=True)),
                ('vai_onibus_sexta', models.BooleanField()),
                ('confirma_ir_sozinho', models.BooleanField()),
                ('horario_chegada_sabado', models.TimeField(blank=True, null=True)),
                ('recebeu_qr_code', models.BooleanField()),
                ('tem_familiar_cjas', models.BooleanField()),
                ('familiar_nome', models.CharField(blank=True, max_length=250)),
                ('compartilhar_cama', models.BooleanField(blank=True, null=True)),
                ('precisa_contato_saude', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('estaca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios', to='cjasPolls.estaca')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formularios', to='cjasPolls.unidade')),
            ],
            options={
                'db_table': 'formularios_cjas',
                'ordering': ['-criado'],
            },
        ),
    ]
