# Generated by Django 6.1 on 2026-08-21 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0003_add_formulario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulariocjas',
            name='confirma_ir_sozinho',
        ),
    ]
