# Generated by Django 6.1 on 2026-08-21 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0004_remocao_confirmar_ir_sozinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='estaca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='cjasPolls.estaca'),
        ),
    ]
