# Generated by Django 6.1 on 2026-08-21 18:23

from django.db import migrations


def popular_estacas(apps, schema_editor):

    Estaca = apps.get_model('cjasPolls','Estaca')

    dados = [
        {"id": 1, "nome": "Guaratinguetá"},
        {"id": 2, "nome": "Guarulhos Cumbica"},
        {"id": 3, "nome": "Guarulhos"},
        {"id": 4, "nome": "São José dos Campos"},
        {"id": 5, "nome": "São José dos Campos Sul"},
        {"id": 6, "nome": "Ipiranga"},
        {"id": 7, "nome": "Itaquá"},
        {"id": 8, "nome": "Itaquera"},
        {"id": 9, "nome": "Mogi das Cruzes"},
        {"id": 10, "nome": "Penha"},
        {"id": 11, "nome": "Sapopemba"},
        {"id": 12, "nome": "São Miguel"}
    ]

    for item in dados:
        Estaca.objects.update_or_create(
            id=item["id"],
            defaults={"nome":item["nome"]}
        )

def reverter_populacao(apps, schema_editor):
    Estaca = apps.get_model('cjasPolls','Estaca')
    ids = [1,2,3,4,5,6,7,8,9,10,11,12]
    Estaca.objects.filter(id__in=ids).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0005_change_type_on_delete_unidade'),
    ]

    operations = [
        migrations.RunPython(popular_estacas, reverter_populacao)
    ]
