# Generated by Django 6.1 on 2026-08-21 18:38

from django.db import migrations

dados_unidades = [
    # --- Guaratinguetá (ID: 1) ---
    {"nome": "Cachoeira Paulista", "estaca_id": 1},
    {"nome": "Campos do Jordão", "estaca_id": 1},
    {"nome": "Cruzeiro", "estaca_id": 1},
    {"nome": "Guaratinguetá", "estaca_id": 1},
    {"nome": "Lorena", "estaca_id": 1},
    {"nome": "Pindamonhangaba", "estaca_id": 1},
    {"nome": "Taubaté 1", "estaca_id": 1},
    {"nome": "Taubaté 2", "estaca_id": 1},

    # --- Cumbica (ID: 2) ---
    {"nome": "Cumbica", "estaca_id": 2},
    {"nome": "Jardim Bela Vista", "estaca_id": 2},
    {"nome": "Jardim Presidente Dutra", "estaca_id": 2},
    {"nome": "Jardim Primavera", "estaca_id": 2},
    {"nome": "Pimentas", "estaca_id": 2},
    {"nome": "Santos Dumont", "estaca_id": 2},
    {"nome": "Vila Any", "estaca_id": 2},
    {"nome": "Nova Cidade", "estaca_id": 2},

    # --- Guarulhos (ID: 3) ---
    {"nome": "Guarulhos", "estaca_id": 3},
    {"nome": "Jardim São Paulo", "estaca_id": 3},
    {"nome": "Continental", "estaca_id": 3},
    {"nome": "Gopoúva", "estaca_id": 3},
    {"nome": "Vila Galvão", "estaca_id": 3},

    # --- São José dos Campos (ID: 4) ---
    {"nome": "Castelli", "estaca_id": 4},
    {"nome": "Jardim Paulista", "estaca_id": 4},
    {"nome": "Vila Ema", "estaca_id": 4},
    {"nome": "Vista Verde", "estaca_id": 4},
    {"nome": "Caçapava", "estaca_id": 4},

    # --- São José dos Campos Sul (ID: 5) ---
    {"nome": "Parque Industrial", "estaca_id": 5},
    {"nome": "Cidade Jardim", "estaca_id": 5},
    {"nome": "Jacareí", "estaca_id": 5},
    {"nome": "Jardim Florida", "estaca_id": 5},
    {"nome": "Jardim Satélite", "estaca_id": 5},
    {"nome": "Morumbi", "estaca_id": 5},

    # --- Ipiranga (ID: 6) ---
    {"nome": "Belém", "estaca_id": 6},
    {"nome": "Monumento", "estaca_id": 6},
    {"nome": "Mooca", "estaca_id": 6},
    {"nome": "São João Clímaco", "estaca_id": 6},
    {"nome": "Vila Mariana", "estaca_id": 6},
    {"nome": "Vila Prudente", "estaca_id": 6},

    # --- Itaquá (ID: 7) ---
    {"nome": "Caiuby", "estaca_id": 7},
    {"nome": "Poá", "estaca_id": 7},
    {"nome": "Vila Virgínia", "estaca_id": 7},
    {"nome": "Arujá", "estaca_id": 7},
    {"nome": "Itaquá", "estaca_id": 7},
    {"nome": "Jardim Odete", "estaca_id": 7},

    # --- Itaquera (ID: 8) ---
    {"nome": "Ferraz", "estaca_id": 8},
    {"nome": "Itaquera", "estaca_id": 8},
    {"nome": "Tiradentes 1", "estaca_id": 8},
    {"nome": "Tiradentes 2", "estaca_id": 8},
    {"nome": "Cidade Líder", "estaca_id": 8},
    {"nome": "Guaianazes", "estaca_id": 8},
    {"nome": "José Bonifácio", "estaca_id": 8},

    # --- Mogi (ID: 9) ---
    {"nome": "Brás Cubas", "estaca_id": 9},
    {"nome": "Guararema", "estaca_id": 9},
    {"nome": "Jundiapeba", "estaca_id": 9},
    {"nome": "Mogi Centro", "estaca_id": 9},
    {"nome": "Suzano", "estaca_id": 9},
    {"nome": "Vila Lavínia", "estaca_id": 9},
    {"nome": "Boa Vista", "estaca_id": 9},

    # --- Penha (ID: 10) ---
    {"nome": "Tatuapé", "estaca_id": 10},
    {"nome": "Penha", "estaca_id": 10},
    {"nome": "Vila Carrão", "estaca_id": 10},
    {"nome": "Vila Esperança", "estaca_id": 10},
    {"nome": "Vila Matilde", "estaca_id": 10},
    {"nome": "Vila Ré", "estaca_id": 10},

    # --- Sapopemba (ID: 11) ---
    {"nome": "Jardim Santo André", "estaca_id": 11},
    {"nome": "Jardim Tietê", "estaca_id": 11},
    {"nome": "Sapopemba", "estaca_id": 11},
    {"nome": "São Mateus", "estaca_id": 11},
    {"nome": "Vila Industrial", "estaca_id": 11},

    # --- São Miguel (ID: 12) ---
    {"nome": "Ermelino Matarazzo", "estaca_id": 12},
    {"nome": "Jardim Camargo Novo", "estaca_id": 12},
    {"nome": "Parque Boturussu", "estaca_id": 12},
    {"nome": "São Miguel", "estaca_id": 12},
    {"nome": "Vila Curuçá", "estaca_id": 12},
    {"nome": "Vila Jacuí", "estaca_id": 12},
    {"nome": "Itaim Paulista", "estaca_id": 12},
    {"nome": "Jardim Romano", "estaca_id": 12}
]

def popular_unidades(apps, schema_editor):
        Unidade = apps.get_model('cjasPolls', 'Unidade')
        Estaca = apps.get_model('cjasPolls', 'Estaca')
        

        for item in dados_unidades:
              estaca = Estaca.objects.get(id=item["estaca_id"])

              Unidade.objects.update_or_create(
                    estaca=estaca,
                    nome=item["nome"],
                    defaults={}
              )

def reverter_unidades(apps, schema_editor):
    Unidade = apps.get_model('cjasPolls', 'Unidade')
    # Opcional: remove caso dê rollback
    nomes = [item["nome"] for item in dados_unidades] if 'dados_unidades' in locals() else []
    Unidade.objects.filter(nome__in=nomes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0006_popular_estacas'),
    ]

    operations = [
        migrations.RunPython(popular_unidades, reverter_unidades),
    ]
