# Generated by Django 6.1 on 2026-08-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0007_popular_alas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocjas',
            name='vai_onibus_sexta',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
