# Generated by Django 6.1 on 2026-08-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0008_alter_formulariocjas_vai_onibus_sexta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocjas',
            name='recebeu_qr_code',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulariocjas',
            name='tem_familiar_cjas',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
