# Generated by Django 6.1 on 2026-08-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cjasPolls', '0009_alter_formulariocjas_recebeu_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocjas',
            name='familiar_nome',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='formulariocjas',
            name='precisa_contato_saude',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
